swagger: "2.0"
info:
  description: "Lightweight Content Polymerizing Engine & Management System"
  title: "Colymer API"
  version: "1.0"
basePath: /api
tags:
  - name: article
    description: "A single article item such as a blog, an email or a tweet etc."
  - name: attachment
    description: "Attachment of the article."
parameters:
  collection:
    name: "collection"
    in: "path"
    description: "Collection name"
    required: true
    type: "string"
  _id:
    name: "_id"
    in: "query"
    description: "Document _id"
    required: true
    type: "string"
produces:
  - "application/json"
consumes:
  - "application/json"
paths:
  /article/{collection}:
    parameters:
      - $ref: "#/parameters/collection"
    get:
      tags:
        - article
      summary: "Query articles"
      description: "Query articles"
      operationId: "queryArticles"
      parameters:
        - name: "query object"
          in: "body"
          description: "Query object"
          required: true
          schema:
            type: "object"
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Article"
        400:
          description: "Invalid Input"
        500:
          description: "Error"
    post:
      tags:
        - article
      summary: "Insert article"
      description: "Insert article. Not override any existing article."
      operationId: "postArticle"
      parameters:
        - name: "auto_attachments"
          in: "query"
          description: "Whether to process attachments automaticly."
          type: "boolean"
          default: false
        - name: "replace"
          in: "query"
          description: "Whether to replace an article with the same id and version already exists."
          type: "boolean"
          default: "false"
        - name: "article"
          in: "body"
          description: "Article object"
          required: true
          schema:
            $ref: "#/definitions/Article"
      responses:
        201:
          description: "Created"
        204:
          description: "Updated"
        400:
          description: "Invalid Input"
        409:
          description: "Conflict"
        500:
          description: "Error"
  /article/{collection}/{_id}:
    parameters:
      - $ref: "#/parameters/collection"
      - $ref: "#/parameters/_id"
    get:
      tags:
        - article
      summary: "Get article"
      description: "Get article"
      operationId: "getArticle"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Article"
        400:
          description: "Invalid Input"
        404:
          description: "Not Found"
        500:
          description: "Error"
    put:
      tags:
        - article
      summary: "Update article"
      description: "Update article."
      operationId: "putArticle"
      parameters:
        - name: "auto_attachments"
          in: "query"
          description: "Whether to process attachments automaticly."
          type: "boolean"
          default: false
        - name: "article"
          in: "body"
          description: "Article object"
          schema:
            $ref: "#/definitions/Article"
      responses:
        204:
          description: "Updated"
        400:
          description: "Invalid Input"
        500:
          description: "Error"
    delete:
      tags:
        - article
      summary: "Delete article"
      description: "Delete article"
      operationId: "deleteArticle"
      responses:
        204:
          description: "OK"
        400:
          description: "Invalid Input"
        404:
          description: "Not Found"
        500:
          description: "Error"
  /upload-info/attachment/{collection}:
    parameters:
      - $ref: "#/parameters/collection"
    get:
      tags:
        - attachment
      summary: "Get the upload method of the attachment"
      description: "Get the upload method of the attachment"
      operationId: "getUploadUrl"
      parameters:
        - name: "path"
          in: "query"
          description: "The path to save attachment"
          required: true
          type: "string"
        - name: "isFormData"
          in: "query"
          description: "Whether to use multipart/form-data to upload file."
          type: "boolean"
          default: false
      responses:
        200:
          description: "OK"
          schema:
            type: "object"
            properties:
              upload:
                type: "object"
                properties:
                  method:
                    type: "string"
                    enum:
                      - POST
                      - PUT
                  url:
                    type: "string"
                  headers:
                    type: "array"
                    items:
                      type: "object"
                      properties:
                        name:
                          type: "string"
                        value:
                          type: "string"
                  formData:
                    type: "array"
                    items:
                      type: "object"
                      properties:
                        name:
                          type: "string"
                        value:
                          type: "string"
                  formField:
                    type: "string"
              file:
                type: "object"
                properties:
                  name:
                    type: "string"
                  url:
                    type: "string"
                  content_type:
                    type: "string"
                  path:
                    type: "string"
        400:
          description: "Invalid Input"
        500:
          description: "Error"
  /attachment/{collection}:
    parameters:
      - $ref: "#/parameters/collection"
      - name: "path"
        in: "query"
        description: "The path to save attachment"
        required: true
        type: "string"
    get:
      tags:
        - attachment
      summary: "Get attachment"
      description: "Get attachment"
      operationId: "getAttachment"
      responses:
        302:
          description: "Found"
        400:
          description: "Invalid Input"
        500:
          description: "Error"
    post:
      tags:
        - attachment
      summary: "Upload attachment through formData"
      description: "Upload attachment through formData (multipart/form-data)"
      operationId: "postAttachment"
      consumes:
        - multipart/form-data
      parameters:
        - name: "file"
          in: "formData"
          description: "Attachment file"
          required: true
          type: "file"
      responses:
        201:
          description: "Created"
        400:
          description: "Invalid Input"
        500:
          description: "Error"
    put:
      tags:
        - attachment
      summary: "Upload attachment directly"
      description: "Upload attachment by FileReader or non-browser."
      operationId: "putAttachment"
      consumes:
        - application/octet-stream
      responses:
        201:
          description: "Created"
        400:
          description: "Invalid Input"
        500:
          description: "Error"
definitions:
  Article:
    type: "object"
    properties:
      id:
        type: "string"
        example: "322"
      author:
        type: "object"
        properties:
          id:
            type: "string"
            example: "5128446"
          name:
            type: "string"
            example: "first author"
      title:
        type: "string"
        example: "Example Title"
      content:
        type: "string"
        example: "This is an example."
      content_type:
        type: "string"
        example: "text/html"
      time:
        type: "string"
        format: "date-time"
      metadata:
        type: "object"
      original_url:
        type: "string"
        example: "http://www.example.com/5128446"
      attachments:
        type: "array"
        items:
          $ref: "#/definitions/Attachment"
      version:
        type: "string"
    required:
      - content
  Attachment:
    type: "object"
    properties:
      id:
        type: "string"
      filename:
        type: "string"
      url:
        type: "string"
        example: "http://example.com/attachment.jpg"
      content_type:
        type: "string"
        example: "image/jpeg"
      original_url:
        type: "string"
        example: "http://example.com/attachment.jpg"
      path:
        type: "string"
      metadata:
        type: "object"
